"""update wechat_user

Revision ID: 0c230e7547ee
Revises: e6041b6ea77b
Create Date: 2025-04-14 10:22:31.937218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c230e7547ee'
down_revision: Union[str, None] = 'e6041b6ea77b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wechat_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('open_id', sa.String(length=50), nullable=False),
    sa.Column('union_id', sa.String(length=50), nullable=True),
    sa.Column('session_key', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wechat_users_id'), 'wechat_users', ['id'], unique=False)
    op.create_index(op.f('ix_wechat_users_open_id'), 'wechat_users', ['open_id'], unique=True)
    op.create_index(op.f('ix_wechat_users_union_id'), 'wechat_users', ['union_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wechat_users_union_id'), table_name='wechat_users')
    op.drop_index(op.f('ix_wechat_users_open_id'), table_name='wechat_users')
    op.drop_index(op.f('ix_wechat_users_id'), table_name='wechat_users')
    op.drop_table('wechat_users')
    # ### end Alembic commands ###
