"""add garbage items2

Revision ID: 45112cbaaba4
Revises: 08c1439173e8
Create Date: 2025-04-20 16:55:15.305309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45112cbaaba4'
down_revision: Union[str, None] = '08c1439173e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garbage_items',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objname', sa.String(), nullable=True),
    sa.Column('classify', sa.String(), nullable=True),
    sa.Column('attention', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garbage_items_id'), 'garbage_items', ['id'], unique=False)
    op.create_index(op.f('ix_garbage_items_objname'), 'garbage_items', ['objname'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_garbage_items_objname'), table_name='garbage_items')
    op.drop_index(op.f('ix_garbage_items_id'), table_name='garbage_items')
    op.drop_table('garbage_items')
    # ### end Alembic commands ###
